se_report:
    resource: "@SEReportBundle/Resources/config/routing.yml"
    prefix:   /report

se_input:
    resource: "@SEInputBundle/Resources/config/routing.yml"
    prefix:   /

se_zest:
    resource: "@SEZestBundle/Resources/config/routing.yml"
    prefix:   /zest
