se_input_home:
    path:     /input
    defaults: { _controller: SEInputBundle:Entry:input }

se_input_employees:
    path:     /input/employees
    defaults: { _controller: SEInputBundle:Settings:employees }

se_input_employees_add:
    path:     /input/employees/add
    defaults: { _controller: SEInputBundle:Settings:employees_add }

se_input_activities:
    path:     /input/activities
    defaults: { _controller: SEInputBundle:Settings:activities }

se_input_activities_add:
    path:     /input/activities/add
    defaults: { _controller: SEInputBundle:Settings:activities_add }

se_input_import_sap:
    path:     /input/import
    defaults: { _controller: SEInputBundle:Import:sap }

se_input_set_import:
    path:     /input/extimport
    defaults: { _controller: SEInputBundle:Import:set }

se_input_welcome:
    path:     /
    defaults: { _controller: SEInputBundle:Entry:welcome }

se_input_review:
    path:     /review
    defaults: { _controller: SEInputBundle:Entry:review }

se_input_ignore:
    pattern:  /review/input/ignore
    defaults: { _controller: SEInputBundle:Entry:ignore }
    requirements:
        _method:  POST

se_input_delete:
    pattern:  /review/input/delete
    defaults: { _controller: SEInputBundle:Entry:delete }
    requirements:
        _method:  POST